services:
  postgres:
    image: 'postgres:latest'
    container_name: 'contractor-db'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=contractor
      - POSTGRES_PASSWORD=contractor
      - POSTGRES_DB=contractor